config/routes.rb
Rails.application.routes.draw do
  
  get 'groups/new'
  get 'answers/new'
  get 'bootfront/page1'
  devise_for :users

  resources :pubs do 
    resources :answers
  end

  #get 'add_member' => 'groups#add_member'
  resources :groups do 
    patch 'add_user'
    resources :users, only: [:create]
    resources :group_pubs
  end

  resources :users


  root 'pubs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :pub
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
    has_many :group_pubs
end

app/models/group_pub.rb
class GroupPub < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/pub.rb
class Pub < ApplicationRecord
    belongs_to :type
    belongs_to :user
    has_many :answers
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :pubs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        # before_action :authenticate_user!
        has_many :pubs
        has_many :answers

        has_many :memberships
        has_many :groups, through: :memberships

        has_many :group_pubs

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :find_pub, only: [:new]

  def new
    find_pub
    @answer = @pub.answers.build
  end

  def edit
    @pub = Pub.find(params[:pub_id])
    @answer = Answer.find(params[:id])
  end

  def create
    find_pub
    @answer = Answer.create(answer_params)
    @answer.user_id = current_user.id 
    @answer.pub_id = @pub.id
    if @answer.save
      #raise @answer.inspect
      redirect_to pub_path(@pub)
    end
  end

  def update
    @pub = Pub.find(params[:pub_id])
    @answer = Answer.find(params[:id])
    @answer = @answer.update(answer_params)
      redirect_to pub_path(@pub)
  end

  def destroy
    @pub = Pub.find(params[:pub_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to pub_path(@pub)
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end

  def find_pub
    @pub = Pub.find(params[:id] || params[:pub_id] )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end

end

app/controllers/bootfront_controller.rb
class BootfrontController < ApplicationController
    def page1
    end
end

app/controllers/group_pubs_controller.rb
class GroupPubsController < ApplicationController

    def new 
       # @group = Group.find(params[:id])
       # @group_pub = @group.group_pubs.build
    end

    def create
        @group = Group.find(params[:group_id]||params[:id])
        #raise @group.inspect
        @group_pub = GroupPub.create(group_pub_params)
        @group_pub.group_id = @group.id
        @group_pub.user_id = current_user.id
        if @group_pub.save
            redirect_to group_path(@group)
        end
    end

    def edit
        find_group
        find_group_pub
    end

    def update 
         find_group
        find_group_pub
        @group_pub.update(group_pub_params)
        if @group_pub.save 
            redirect_to group_path(@group)
        end
    end

    def destroy
        find_group
        find_group_pub
        @group_pub.destroy
        redirect_to group_path(@group)
    end

    private
    def group_pub_params
        params.require("group_pub").permit(:content)
    end

    def find_group
        @group = Group.find(params[:group_id])
    end

    def find_group_pub
        @group_pub = GroupPub.find(params[:id])
    end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper

  def new
    @group = Group.new
  end

  def show
   find_group
  # @group_pub = GroupPub.new
   @group_pub = current_user.group_pubs.build
  end

  def create
    @group = Group.create(group_params)
    @group.users << current_user
   # current_user.groups << @group
    if @group.save
      flash[:notice] = "Group Created"
      redirect_to group_path(@group)
    end
  end

  def add_user
   # redirect_to :error unless @user
    find_group
    find_and_add_user
    redirect_to group_path(@group)
  end




  def error 
    render plain: "Error"
  end

  private
  def group_params
    params.require(:group).permit(:id, :name, :description, :memberships)
  end

  def new_group_user_params
    params.require(:group).require(:users).permit(:name)
  end

  def find_group
   # @group = Group.find(params[:id])
   id = params[:group_id] || params[:id]
  @group = Group.find(id)
  end

end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController

    before_action :find_pub, only: [:show, :edit, :update, :destroy]

    def index
        @pubs = Pub.all
        #aise params[:type].inspect
        @pubs = Pub.all.order("updated_at DESC")
        if params[:type]
            @type_id = Type.find_by(name: params[:type]).id
            @pubs = Pub.where(type_id: @type_id)
        end
        if user_signed_in?
        @group = Group.where(:user_id => current_user.id)
        end
    end

    def show 
    end

    def new 
        #@pub = Pub.new
        @pub = current_user.pubs.build
        @types = Type.all.map{ |t| [t.name, t.id] }
    end

    def create
            @pub = Pub.create(pub_params)
            @pub.type_id = params[:type_id]
            @pub.user_id = current_user.id
            @pub.save
            redirect_to pubs_path
    end

    def edit
    end

    def update
        @pub.type_id = params[:type_id]
        @pub.update(pub_params)
        redirect_to pubs_path
    end

    def destroy
        @pub.destroy
        redirect_to pubs_path
    end

    private
    def pub_params
        params.require(:pub).permit(:content, :type_id)
    end

    def find_pub 
        @pub = Pub.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user  = User.new
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_pubs_helper.rb
module GroupPubsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper

    def find_and_add_user
       find_user
       find_group

      if find_group && find_user
          if !@user.groups.include?(@group)
            @user.groups << @group
            flash[:notice] = success
          else
            flash[:alert] = included
          end
      else
          flash[:alert] = unfound
      end

    end

    
      def find_user
       @user = User.find_by(:name => new_group_user_params[:name])
        #User.find_by(:name => "Rachid")
      end
    
      def unfound
        "We can't find  #{new_group_user_params[:name]} please try with another name"
      end

      def success 
        " Succesful added  #{new_group_user_params[:name]} "
      end

      def included
        " #{new_group_user_params[:name]} has already been added to this group "
      end

end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
                <div class="alert alert-info" role="alert">
                    <p> <%= answer.user.name %> </p>
                    <%= answer.updated_at %>
                    <p class="text-dark font-weight-bold" > <%= answer.content %> </p>    

                    <br>
                    <%= link_to "Edit", edit_pub_answer_path(answer.pub, answer) %> |
                    <%= link_to "Delete", pub_answer_path(answer.pub, answer), method: :delete, data:{confirm: "Delete ?"} %>
                </div>

app/views/answers/_form.html.erb
<%= simple_form_for([ @pub, @answer] ) do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<h2> Edit Pub Answers </h2>

<%= simple_form_for([ @pub, @answer] ) do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.submit %>
<% end %>

app/views/answers/new.html.erb
<div class="row">
    <div class="col-md-12" >
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
          <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-success"> <%= @pub.type.name %> </strong>
            <h3 class="mb-0">
              <a class="text-dark" > <%= @pub.user.name %> </a>
             
            </h3>
            <div class="mb-1 text-muted"> <%= @pub.created_at %> </div>
            <p class="card-text "> <%= @pub.content %> </p>
          </div>
        <!-- <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16c9a9f0e9d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16c9a9f0e9d%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2255.6015625%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="width: 200px; height: 250px;"> -->  
        </div>
      </div>
</div>
<br> <br>  
<dt class="text-primary" > Say something about that </dt> 

<%= render 'form' %>

<style>
        .align-items-start {
      -ms-flex-align: start!important;
      align-items: flex-start!important;
      background: #cdbae8;
      /* border-radius: 15px; */
  }

  .text-success {
            color: #182984!important;
        }

  
  </style>

app/views/bootfront/page1.html.erb
<body>
    <nav class="navbar" style="background-color: rgba(30, 27, 219, 0.226)">
        <div class="container">
            container of my navbar 
        </div>
    </nav>

    <header style="background-color:chartreuse " >
        <div class="container" style="height: 5em">
            container of header
        </div>
    </header>

    <section style="background-color: darkcyan" id="breadcumb">
        <div class="container">
            container of section
        </div>
    </section>

    <!-- the big section-->

    <section>
        <div class="row">
            <div class="container">
                    <div class="col-md-3" style="background-color: darkmagenta">
                        <div class="list-group">
                            <a href="" class="list-group-item"> list-group-item active </a>
                            <a href="" class="list-group-item"> list-group-item  </a>
                            <a href="" class="list-group-item"> list-group-item  </a>
                            <a href="" class="list-group-item"> list-group-item  </a>
                        </div>
                    <div class="well">
                        that's a well
                    </div>
                    </div>


                    <col-md-9 class="col-md-9" style="background-color: darkred"> col-md-9 
                        <div class="panel panel-default"> panel panel-default 1 </div>
                        <div class="panel panel-default"> panel panel-default 2 </div>
                    </col-md-9>
            </div>
        </div>
    </section>

</body>

app/views/group_pubs/_group_pub_form.html.erb
<%= form_for [group, group_pub] do |f| %>
    <%= f.hidden_field :group_id %>
    <%= f.text_area :content, as: :text, class:"my-input", placeholder:"Type your post"%>
    <%= f.submit "Share on group", class:"btn btn-primary"%>
<% end %>

app/views/group_pubs/edit.html.erb
<h2> Edit Group_pub </h2>
<%= render partial: 'group_pub_form', locals:{ group_pub: @group_pub, group: @group } %>

app/views/group_pubs/new.html.erb
Publish to group
<%#= render partial: 'group_pub_form', locals:{ group_pub: @group_pub, group: @group } %>
<%= render 'group_pub_form' %>

app/views/groups/_add_member_form.html.erb
<%= form_for group, :url => group_add_user_path(group) do |f| %>
    <%= f.fields_for :users, group.users.build do |user_fields|%>
        <%= user_fields.text_field :name, class:"form-control", placeholder: "Add member by username" %>
        <%= user_fields.submit "Add User" , class:"btn btn-primary mb-2" %>
    <% end %>
<% end %>

app/views/groups/_group_form.html.erb
<%= simple_form_for (@group) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.submit %>
<% end %>

app/views/groups/new.html.erb
<%= render 'group_form' %>

app/views/groups/show.html.erb
<div class="row row-one">
        <div class="col-md-4">
                <p> Goup Name </p>
                <h4 class="font-weight-bold"> <%= @group.name %> </h4> 
                <br>   
                <p> Group Admin </p>
                <h4 class="font-weight-bold"> <%= @group.users.last.name %> </h4>
        </div>
        
        <div class="col-md-4">
                <h4 class="font-weight-bold" > Group Description </h4> <%= @group.description %> <br>
                <h3\> Add User: </h3> <br>
                <%= render partial: 'add_member_form', locals: {group: @group} %>
        </div>
        
        <div class="col-md-4">
                <h4 class="font-weight-bold" > Group Members </h4>
                <% @group.users.each do |user| %>
                    <p class="badge badge-pill badge-primary"><%=user.name%></p>
                <% end %>        
        </div>
</div>

<br> <br> <br>

<div class="row">
    <div class="col-md-4">
            <h4 class="font-weight-bold" > Share With Your Peers </h4> <br>
            <%= render partial: 'group_pubs/group_pub_form', locals: {group: @group, group_pub: @group_pub} %>
    </div>

    <div class="col-md-8">
        <% if @group.group_pubs.blank? %>
            <h4> No message </h4>
        <% end %>
        <% @group.group_pubs.each do |pub| %>
            <div class="alert alert-primary" role="alert">
                    <%= pub.content %>
                    <% if user_signed_in? && pub.user_id == current_user.id %>
                    <%= link_to "Edit group_pub", edit_group_group_pub_path(group_id: @group.id, id: pub.id) %>
                    <%= link_to "Delete", group_group_pub_path(@group.id, pub.id), method: :delete, data: {confirm: "Delete Post"} %>
                    <% end %>
            </div>
        <% end %>
    </div>

</div>


<style>
    .row-one{
        margin-right: -15px;
    margin-left: -15px;
    background-color: #fcfcff;
    }


.form-control {
    display: inline;
    width: 250px;
    height: 34px;
    /* padding: 6px 12px; */
    font-size: 14px;
    line-height: 30;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    vertical-align: bottom;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

input, button, select, textarea {
    font-family: inherit;
    font-size: inherit;
    margin-bottom: 5px;
    display: block;
    line-height: inherit;
}

.my-input {
    margin-top: 0px;
    margin-bottom: 5px;
    height: 120px;
    width: 100%;
}

.badge {
    display: inline-block;
    min-width: 20px;
    padding: 3px 7px;
    font-size: 12px;
    font-weight: 700;
    line-height: 2;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    background-color: #d88c2a;
    border-radius: 10px;
}

button, html input[type=button], input[type=reset], input[type=submit] {
    -webkit-appearance: button;
    cursor: pointer;
    float: left;
}

</style>

app/views/pubs/_form.html.erb
<%= simple_form_for(@pub) do |f| %>
    <%= select_tag(:type_id, options_for_select(@types), prompt: "Publication Type", class: "link" ) %>
    <%= f.input :content, as: :text, placeholder: "Share something or ask a question", required: true, hint: "this publication will be public" %>
    <%= f.submit %>
<% end %>

app/views/pubs/edit.html.erb
<%= simple_form_for(@pub) do |f| %>
<%= f.collection_select(:type_id, Type.all, :id, :name, :prompt => "Pick a category", :class => 'btn btn-primary' ) %>
    <%= f.input :content, as: :text, placeholder: "Share something or ask a question", required: true, hint: "this publication will be public", class: "card-text" %>
    <%= f.submit %>
<% end %>

app/views/pubs/index.html.erb
<% if user_signed_in? %>

            <div class="dropdown create">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sort by language
                
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                   <% Type.all.each do |type| %>
                      <li class=" <%  'active' if params[:type] == type.name %> " > 
                        <%= link_to type.name, pubs_path(type: type.name) %>
                      </li>
                  <% end %>
              </ul>

              <a  href="/groups/new" class="btn btn-primary" > CREATE LEARNING GROUP </a>

            </div>

  <div class="col-md-8">
        <% @pubs.each do |pub| %>
        <div class="col-md-6">
            <a href="/pubs/<%=pub.id%> ">
              <div class="card flex-md-row mb-4 box-shadow h-md-250">
                  <div class="card-body d-flex flex-column align-items-start">
                    <strong class="d-inline-block mb-2 text-success"> <%= pub.type.name %> </strong>
                    <h3 class="mb-0">
                      <a class="text-dark" > <%= pub.user.name %> </a>
                    </h3>
                    <div class="mb-1 text-muted"> <%= pub.created_at %> </div>
                    <p class="card-text mb-auto"> <%= pub.content %> </p> <br>
                  </div>
                <!-- <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16c9a9f0e9d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16c9a9f0e9d%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2255.6015625%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="width: 200px; height: 250px;"> -->  
                </div>
          </a>
          <a href="/pubs/<%=pub.id%>" class="font-weight-bold" > <%= pub.answers.size %> comments </a>
         </div>
          <% end %>
  </div>

    <div class="col-md-4">
      <h1 class="text-success" > GROUPS YOU JOINED </h1>
        <h2> Hello <%= current_user.name %>, </h2> <br><br>
        <h4> Don't miss out on what your peers are discussing</h4>
         <h4> We're sure they are great stuffs to learn from group discussions </h4>
        <br>
       <% current_user.groups.each do |group| %>
          <%= link_to group.name, group_path(group), :class => 'btn btn-outline-success btn-custom' %>
       <% end %>
   </div>

<% else %>
  <h2> Please Sign in to see what other learners are sharing ... </h2>

<% end %>

<style>
.btn-custom {
    height: 120px;
    width: 120px;
    padding-top: 45px;
    margin-right: 4px;
}
</style>

app/views/pubs/show.html.erb
<div class="row">
    <div class="col-md-12" >
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
          <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-success"> <%= @pub.type.name %> </strong>
            <h3 class="mb-0">
              <a class="text-dark" > <%= @pub.user.name %> </a>
             
            </h3>
            <div class="mb-1 text-muted"> <%= @pub.created_at %> </div>
            <p class="card-text"> <%= @pub.content %> </p>
          </div>
        <!-- <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16c9a9f0e9d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16c9a9f0e9d%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2255.6015625%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="width: 200px; height: 250px;"> -->  
        </div>
      </div>
</div>


<div class="row">
  <div class="col-md-5">
      <%= render @pub.answers %>
  </div>  

  <div class="col-md-7">
      <% if user_signed_in? && @pub.user_id == current_user.id %>
      <a  href="/pubs/<%=@pub.id%>/edit/" class="btn btn-primary float-left" > EDIT </a> 
      <a class="btn btn-danger " href="/pubs/<%=@pub.id%>" data-method="delete" class="btn btn-primary" data-confirm="You're about to delete this post" > DELETE </a> <br><br>
  <% end %>
      <a  href="/pubs/<%=@pub.id%>/answers/new" class="btn btn-primary float-left" > Say something </a> 
  </div>

</div>

<style>
  .btn-primary {
  color: #fff;
  background-color: #428bca;
  margin-right: 10px;
  border-color: #357ebd;
  float: right;
}

.alert-info {
    color: #31708f;
    background-color: #ffffff;
    border-color: #1571ca;
    border-width: 1px;
}

</style>

app/views/users/welcome.html.erb
<h1>Welcome</h1>
<%= link_to "Sign Up", new_user_registration_path %>
<%= link_to "Create Pub", new_pub_path %>
<%= link_to "Log Out", destroy_user_session_path, method: :delete %>